apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coral-agent
  namespace: coral-system
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-coral-agent-0
      containers:
        - name: operator
          image: docker.io/golang:latest
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - infinity
          workingDir: /usr/src/app
          volumeMounts:
            - name: app
              mountPath: /usr/src/app
              readOnly: true
      volumes:
        - name: app
          hostPath:
            path: /app