apiVersion: apps/v1
kind: Deployment
metadata:
  name: coral-controller
  namespace: coral-system
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: operator
          image: docker.io/golang:latest
          imagePullPolicy: IfNotPresent
          workingDir: /usr/src/app
          command:
            - sleep
            - infinity
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            capabilities:
              add: ["SETFCAP"]
          ports:
            - containerPort: 9443
              name: webhook
              protocol: TCP
          volumeMounts:
            - name: app
              mountPath: /usr/src/app
              readOnly: true
      volumes:
        - name: app
          hostPath:
            path: /app