---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror
  namespace: coral
  labels:
    app: coral
    component: mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coral
      component: mirror
  template:
    metadata:
      labels:
        app: coral
        component: mirror
    spec:
      containers:
        - name: mirror
          image: docker.io/strataviz/coral:latest
          imagePullPolicy: IfNotPresent
          command:
            - coral
            - mirror
            - --log-level=4
            - --namespace=coral
            - --labels=app=coral,component=mirror
          ports:
            - containerPort: 9090
