apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coral-system
commonAnnotations:
  ctx.sh/authors: "Coral Authors"
  ctx.sh/license: "Apache"
  ctx.sh/support: "https://github.com/ctxswitch/coral/issues"
  cert-manager.io/inject-ca-from: coral/coral-webhook-cert
patches:
  - target:
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-configuration
    patch: |-
      apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      metadata:
        name: mutating-webhook-configuration
      webhooks:
        - name: minjector.image.coral.ctx.sh
          namespaceSelector:
            matchExpressions:
              - key: image.coral.ctx.sh/inject
                operator: In
                values: ["true"]
  # TODO: Merge all but the metadata name target to the inline patch
  - target:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
    patch: |-
      - op: replace
        path: /metadata/name
        value: coral-webhook
      - op: replace
        path: /webhooks/0/clientConfig/service/name
        value: coral-webhook-service
      - op: replace
        path: /webhooks/0/clientConfig/service/namespace
        value: coral-system
  - target:
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-configuration
    patch: |-
      - op: replace
        path: /metadata/name
        value: coral-webhook
      - op: replace
        path: /webhooks/0/clientConfig/service/name
        value: coral-webhook-service
      - op: replace
        path: /webhooks/0/clientConfig/service/namespace
        value: coral-system
      - op: replace
        path: /webhooks/1/clientConfig/service/name
        value: coral-webhook-service
      - op: replace
        path: /webhooks/1/clientConfig/service/namespace
        value: coral-system
resources:
  - certs.yaml
  - manifests.yaml
  - service.yaml
