---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ctx-sh-v1-image
  failurePolicy: Fail
  name: mimage.coral.ctx.sh
  rules:
  - apiGroups:
    - coral.ctx.sh
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - images
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ctx-sh-v1-mirror
  failurePolicy: Fail
  name: mmirror.coral.ctx.sh
  rules:
  - apiGroups:
    - coral.ctx.sh
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mirrors
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ctx-sh-v1-image
  failurePolicy: Fail
  name: vimage.coral.ctx.sh
  rules:
  - apiGroups:
    - coral.ctx.sh
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - images
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ctx-sh-v1-mirror
  failurePolicy: Fail
  name: vmirror.coral.ctx.sh
  rules:
  - apiGroups:
    - coral.ctx.sh
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mirrors
  sideEffects: None
