---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-coral-ctx-sh-v1beta1-imagesync
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mimagesync.coral.ctx.sh
  rules:
  - apiGroups:
    - coral.ctx.sh
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - imagesyncs
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /inject-coral-ctx-sh-v1beta1-imagesync
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: minjector.coral.ctx.sh
  rules:
  - apiGroups:
    - apps
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
    - daemonsets
    - deployments
    - jobs
    - replicasets
    - replicationcontrollers
    - statefulsets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-coral-ctx-sh-v1beta1-imagesync
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vimagesync.coral.ctx.sh
  rules:
  - apiGroups:
    - coral.ctx.sh
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - imagesyncs
  sideEffects: None
