apiVersion: v1
kind: Service
metadata:
  labels:
    group: coral
    app: controller
  name: coral-webhook-service
  namespace: coral-system
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    group: coral
    app: controller
