apiVersion: v1
kind: Service
metadata:
  labels:
    app: coral
  name: coral-webhook-service
  namespace: coral
spec:
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
      nodePort: 30100
  selector:
    app: coral
