version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - cyclop
    - errcheck
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - map
    funlen:
      lines: 100
      statements: 55
    gocognit:
      min-complexity: 20
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: false
    lll:
      line-length: 210
      tab-width: 1
    nakedret:
      max-func-lines: 10
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - lll
        path: _test\.go
      - linters:
          - gochecknoglobals
        path: apis/*
      - linters:
          - gochecknoglobals
        path: metrics.go
      - linters:
          - lll
        path: webhook.go
    paths:
      - tmp
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - tmp
      - third_party$
      - builtin$
      - examples$
