---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-stvz-io-v1-builder
  failurePolicy: Fail
  name: mbuilder.stvz.io
  rules:
  - apiGroups:
    - stvz.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - builders
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-stvz-io-v1-builder
  failurePolicy: Fail
  name: vbuilder.stvz.io
  rules:
  - apiGroups:
    - stvz.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - builders
  sideEffects: None
