---
apiVersion: v1
kind: Pod
metadata:
  name: crictl
  namespace: coral-system
spec:
#  serviceAccountName: coral-system
  terminationGracePeriodSeconds: 5
  nodeSelector:
    kubernetes.io/hostname: k3d-coral-agent-0
  containers:
    - name: crictl
      image: dojobits/crictl:v1.30.0
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - infinity
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
      volumeMounts:
        - name: containerd
          mountPath: "/run/containerd"
  volumes:
    - name: containerd
      hostPath:
        path: /run/k3s/containerd
