apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coral
commonAnnotations:
  strata.stvz.io/authors: "StrataViz"
  strata.stvz.io/license: "Apache"
  strata.stvz.io/support: "https://github.com/strataviz/coral/issues"
resources:
  - role.yaml
  - service-account.yaml
  - cluster-role-binding.yaml
