---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coral-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - stvz.io
  resources:
  - buildqueues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stvz.io
  resources:
  - buildqueues/finalizers
  verbs:
  - update
- apiGroups:
  - stvz.io
  resources:
  - buildqueues/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stvz.io
  resources:
  - buildset
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stvz.io
  resources:
  - buildset/finalizers
  verbs:
  - update
- apiGroups:
  - stvz.io
  resources:
  - buildset/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stvz.io
  resources:
  - watchset
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stvz.io
  resources:
  - watchset/finalizers
  verbs:
  - update
- apiGroups:
  - stvz.io
  resources:
  - watchset/status
  verbs:
  - get
  - patch
  - update
