---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coral-role
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stvz.io
  resources:
  - builders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stvz.io
  resources:
  - builders/finalizers
  verbs:
  - update
- apiGroups:
  - stvz.io
  resources:
  - builders/status
  verbs:
  - get
  - patch
  - update
