---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coral
  namespace: coral
  labels:
    app: coral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coral
  template:
    metadata:
      labels:
        app: coral
    spec:
      serviceAccountName: coral-system
      containers:
        - name: controller
          image: coral:staging
          imagePullPolicy: IfNotPresent
          workingDir: /usr/src/app
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          command:
            - /coral
            - controller
            - --log-level=8
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: app
              mountPath: /usr/src/app
            - name: tls
              mountPath: "/etc/webhook/tls"
              readOnly: true
      volumes:
        - name: app
          hostPath:
            path: /app
        - name: tls
          secret:
            secretName: coral-webhook-cert