apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  strata.stvz.io/authors: "StrataViz"
  strata.stvz.io/license: "Apache"
  strata.stvz.io/support: "https://github.com/strataviz/coral/issues"
resources: 
 - ../../base
 - secret.yaml
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: coral
      namespace: coral
  - path: daemonset.yaml
    target:
      kind: DaemonSet
      name: coral-agent
      namespace: coral
