apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
  namespace: coral
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: coral
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: docker.io/registry:2.8.3
          imagePullPolicy: IfNotPresent
          command:
            - registry
            - serve
            - /etc/docker/registry/config.yml
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
          ports:
            - containerPort: 5000
