---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper
  annotations:
    image.stvz.io/inject: pull-policy,selectors
  labels:
    app: sleeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      labels:
        app: sleeper
    spec:
      containers:
        - name: sleepytime
          image: docker.io/library/debian:bullseye-slim
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - infinity