apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint
  namespace: coral
data:
  entrypoint.sh: |
    #!/bin/sh
    set -e
    apt-get update && apt-get install -y libbtrfs-dev libgpgme-dev libdevmapper-dev
    exec $@
