apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  strata.ctx.sh/authors: "StrataViz"
  strata.ctx.sh/license: "Apache"
  strata.ctx.sh/support: "https://github.com/strataviz/coral/issues"
resources: 
 - ../../base
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: coral
      namespace: coral

secretGenerator:
  - name: coral-github-secrets
    literals:
    - token=${CORAL_GITHUB_TOKEN}

generatorOptions:
  disableNameSuffixHash: true
