---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror
  namespace: coral
  labels:
    app: coral
    component: mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coral
      component: mirror
  template:
    metadata:
      labels:
        app: coral
        component: mirror
    spec:
      serviceAccountName: coral-system
      containers:
        - name: mirror
          image: docker.io/golang:latest
          imagePullPolicy: IfNotPresent
          workingDir: /usr/src/app
          command:
            - /entrypoint.sh
          args:
            - sleep
            - infinity
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: app
              mountPath: /usr/src/app
            - name: entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
      volumes:
        - name: app
          hostPath:
            path: /app
        - name: entrypoint
          configMap:
            name: entrypoint
            defaultMode: 0755
