---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror
  namespace: coral
  labels:
    app: coral
    component: mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coral
      component: mirror
  template:
    metadata:
      labels:
        app: coral
        component: mirror
    spec:
      containers:
        - name: mirror
          image: docker.io/golang:latest
          imagePullPolicy: IfNotPresent
          workingDir: /usr/src/app
          command:
            - go
            - run
            - main.go
            - mirror
            - --log-level=8
            - --namespace=coral
            - --labels=app=coral,component=mirror
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: app
              mountPath: /usr/src/app
      volumes:
        - name: app
          hostPath:
            path: /app
