apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  ctx.sh/authors: "StrataViz"
  ctx.sh/support: "https://github.com/strataviz/coral/issues"
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/group: cert-manager
resources:
  - namespace.yaml
  - cert-manager-crd.yaml
  - cert-manager.yaml
