---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coral-agent
  namespace: coral-system
  labels:
    group: coral
    app: agent
spec:
  selector:
    matchLabels:
      group: coral
      app: agent
  template:
    metadata:
      labels:
        group: coral
        app: agent
    spec:
      serviceAccountName: coral-system
      containers:
        - name: operator
          image: docker.io/ctxsh/coral:latest
          imagePullPolicy: IfNotPresent
          command:
            - /coral
            - agent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: containerd
              mountPath: "/run/containerd"
      volumes:
        # TODO: Fix me before release
        - name: containerd
          hostPath:
            path: /run/k3s/containerd
