---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coral-controller
  namespace: coral-system
  labels:
    group: coral
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      group: coral
      app: controller
  template:
    metadata:
      labels:
        group: coral
        app: controller
    spec:
      serviceAccountName: coral-system
      containers:
        - name: operator
          image: docker.io/ctxsh/coral:latest
          imagePullPolicy: IfNotPresent
          command:
            - /coral
            - controller
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
          ports:
            - containerPort: 9090
            - containerPort: 9443
          volumeMounts:
            - name: tls
              mountPath: "/etc/coral/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: coral-webhook-cert
